### ISSUE TITLE
FlutterDesktopGpuSurfaceDescriptor undefined

### ISSUE THREAD

**Issue by MindStudioOfficial** [alexmercerind/flutter-windows-ANGLE-OpenGL-Direct3D-Interop#2]
Hey, I was trying to run the example provided but I get build errors becasue "identifier `FlutterDesktopGpuSurfaceDescriptor` is undefined" in `windows\flutter_windows_angle_d3d_texture_plugin.h` (line 74)

Also missing are `kFlutterDesktopPixelFormatBGRA8888`, `flutter::GpuSurfaceTexture` and some others

I am on the master channel of flutter:

```
Flutter (Channel master, 3.1.0-0.0.pre.2114, on Microsoft Windows [Version
    10.0.19044.1865], locale de-DE)
    • Flutter version 3.1.0-0.0.pre.2114 on channel master at C:\src\flutter   
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 5c44057d85 (6 minutes ago), 2022-08-06 08:12:06 +1000 
    • Engine revision da4455d9c9
    • Dart version 2.19.0 (build 2.19.0-70.0.dev)
    • DevTools version 2.16.0
```

Am I missing something?

**Comment by alexmercerind** [comment]
You must be on `master` channel at the moment.

**Comment by MindStudioOfficial** [comment]
I am, that is the weird thing

**Comment by alexmercerind** [comment]
I'm still able to run the project after freshly cloning the repository.
Chances are your bundled headers/shared-libraries aren't updated for some reason.

**Comment by MindStudioOfficial** [comment]
I ran these commands in the following order:

`flutter channel master`
`flutter upgrade`
`flutter clean`
`flutter pub get`

and when looking at the `texture_registrar.h` file it only contains the two classes `PixelBufferTexture` and `TextureRegistrar`

I did this on my main PC and my Laptop with a fresh install of the Flutter SDK with the same results.

**Comment by alexmercerind** [comment]
I recall facing same trouble when fetching these headers, but can't recall very much. It's been many days. You're own your own for this one. Apologies!

**Comment by MindStudioOfficial** [comment]
Running the upgrade, clean and pub get commands in the `example` directory again fixed it for some reason.
