### ISSUE TITLE
[Bug] Crash on Windows 7 SP1

### ISSUE THREAD

**Issue by sudongg** [alexmercerind/flutter-windows-ANGLE-OpenGL-Direct3D-Interop#3]
I try to run on win7 and get a crash
```

Problem signature :
Problem event name : APPCRASH
Application name : flutter_windows_angle_d3d_texture_example.exe
Application version : 1.0.0.0
Application Timestamp : 63116ca2
Fault Module name : flutter_windows_angle_d3d_texture_plugin.dll
Fault Module Version : 0.0.0.0
Fault Module Timestamp: 63116c98
Exception Code : c0000005
Exception Offset : 00000000000032a1
OS Version : 6.1.7601.2.1.0.768.2
Locale ID: 2052
Additional Information 1: 0336
Additional Information 2: 03364a7e80ae3f1737cf664e35c02d23
Additional Information 3: 248b
Additional Information 4: 248b1bdd3e8b77476ea68023c7d3ef5a
```

**Comment by alexmercerind** [comment]
I don't have a device which supports Windows 7, so I can't help.

Either-way, this information you shared is of literally zero use.
A meaningful crash stack-trace along-side (with debug symbols) still could be somewhat helpful.

Sorry.

**Comment by sudongg** [comment]
I tried to troubleshoot the problem. At first, D3D11CreateDevice failed. I tried to change it to
```

    const D3D_FEATURE_LEVEL featureLevels[] = {
        D3D_FEATURE_LEVEL_11_0, D3D_FEATURE_LEVEL_10_1, D3D_FEATURE_LEVEL_10_0,
        D3D_FEATURE_LEVEL_9_3,  D3D_FEATURE_LEVEL_9_2,  D3D_FEATURE_LEVEL_9_1,
    };

#ifndef NDEBUG
    unsigned int flags =
        D3D11_CREATE_DEVICE_BGRA_SUPPORT | D3D11_CREATE_DEVICE_DEBUG;
#else
    unsigned int flags = D3D11_CREATE_DEVICE_BGRA_SUPPORT;
#endif


    if (FAILED(hr = ::D3D11CreateDevice(
                   NULL, D3D_DRIVER_TYPE_HARDWARE, NULL, flags, featureLevels,
                   ARRAYSIZE(featureLevels), D3D11_SDK_VERSION, &d3d11_device_,
                   NULL, &d3d11_device_context_))) {
      MessageBoxW(nullptr, L"D3D11CreateDevice FAILED.", L"Error", MB_OK);
      std::cerr << "D3D11CreateDevice FAILED." << std::endl;
    }

```
Success, then eglInitialize fails, I add in default_display_attributes fl9_3_display_attributes warp_display_attributes
EGL_PLATFORM_ANGLE_TYPE_D3D9_ANGLE is successful, but no content is displayed. I think the current eglInitialize only supports d3d9, but created D3D11Device and D3D11Texture, so nothing is displayed。

My purpose is to display video with libmpv, I don't know how much improvement using RegisterTexture will be compared to using bitmap, I know you are doing research on this, when can I see the results?

**Comment by alexmercerind** [comment]
> I know you are doing research on this, when can I see the results?

I have already made video render & play successfully using libmpv inside Flutter Windows & Linux. I cannot afford to share my work publicly without any funding. It's very performant (due to hardware acceleration) even after screen recording.

And, it's written in 100% Dart, only `Video` widget code is in C/C++. Same is being used in [Harmonoid](https://harmonoid.com).

https://user-images.githubusercontent.com/28951144/188120009-aa9d606a-fd7f-4f28-8dbe-58d3c06d5145.mp4

**Comment by sudongg** [comment]
Thank you for your current work. I will try to use this on win7 again. If there is any progress, I will tell you.

**Comment by alexmercerind** [comment]
I just got Windows 7 installed in a VM. I can confirm the crash.
I will try to fix this soon. Seems to be some kind of bad memory access.

**Comment by alexmercerind** [comment]
Hi @sudongg!

Apologies for the delay, I've been caught up with exams, college & life.

I added a fallback Direct3D 9 based initialization now, everything seems to succeed & therea are no crashes either. But, nothing shows on my Windows 7 VM (plain transparent `Texture`). On Windows 11, [the `glFlush` call makes everything visible](https://github.com/alexmercerind/flutter-windows-ANGLE-OpenGL-Direct3D-Interop/blob/f2b35069c5f492263fda5a1c26903b7c60220c7a/windows/flutter_windows_angle_d3d_texture_plugin.cc#L140-L143). But `glFlush` isn't the best thing here. I will appreciate if you can test or fix for Windows 7 (I only have VM).

I have created a new [`ANGLESurfaceManager`](https://github.com/alexmercerind/flutter-windows-ANGLE-OpenGL-Direct3D-Interop/blob/f2b35069c5f492263fda5a1c26903b7c60220c7a/windows/angle_surface_manager.h#L17-L29) class to easily host open-gl inside Flutter Windows.

BTW, I'll be making a new libmpv based video library public soon, as you asked above (using some of the work here): https://github.com/alexmercerind/dart_vlc/issues/345.

Hoping for the best!

**Comment by alexmercerind** [comment]
One more information I'd like to give is that if I force Direct3D 9 (i e. remove `InitializeD3D11`), it works on Windows 11. So, Direct3D 9 configuration seems to be correct.

**Comment by sudongg** [comment]
@alexmercerind 
It's a pity that I'm also a Windows 7 VM. I've already implemented opengl3 + dx9 to display mpv content on win7, but using skia is not flutter.
The playback effect is similar to that of using MPV directly.
I haven't implemented it yet on flutter.

**Comment by alexmercerind** [comment]
> @alexmercerind It's a pity that I'm also a Windows 7 VM.

> I've already implemented opengl3 + dx9 to display mpv content on win7, but using skia is not flutter. The playback effect is similar to that of using MPV directly. I haven't implemented it yet on flutter.

I have also done it in Flutter with hardware accelerated libmpv video rendering (D3D 11 backing & D3D 9 fallback).
Testing Windows 7 & ensure correct functioning is important. I'm not much sure if buffers swapping is causing the issue.

https://user-images.githubusercontent.com/28951144/188120009-aa9d606a-fd7f-4f28-8dbe-58d3c06d5145.mp4

**Comment by alexmercerind** [comment]
Can you see my Direct3D device & texture initialization or buffer swapping etc. (in this repository) & compare with yours?
I want this to work on Windows 7.

**Comment by alexmercerind** [comment]
I conclude my research.
It is not possible to use ANGLE on Windows 7 with Flutter Windows hardware-accelerated textures i.e. `FlutterDesktopGpuSurfaceType`.

When hosting ANGLE with Direct3D, we have two options:
- `eglCreatePbufferFromClientBuffer` + `EGL_D3D_TEXTURE_2D_SHARE_HANDLE_ANGLE`.
- `eglCreateWindowSurface` + `HWND` (used in Flutter & Chromium).

The texture API gives ability to share a `HANDLE`, which isn't working on Windows 7.
In-fact, when I force mpv to use `eglCreatePbufferFromClientBuffer` with `--hwdec=dxva2 --gpu-context=angle --angle-egl-windowing=no`, it falls back to non-ANGLE plain D3D hwdec on Windows 7. On the other hand, `--angle-egl-windowing=yes` keeps ANGLE running on Windows 7.

I think you also utilized `eglCreateWindowSurface` in your Skia rendering. If not so, I'd like to get informed.

**Comment by sudongg** [comment]
In fact, my project is an opengl3 project, dx is not necessary, nor is skia.
mpv can be directly displayed on opengl3 through mpv_render_context_create (glBindTexture, glTexImage2D), 
and the performance is almost the same as window playback.
But native opengl3 does not have advanced drawing functions out of the box, 
so I introduced skia (via GrDirectContext::MakeGL), and through some processing, skia and native Texture can be well combined.
![image](https://user-images.githubusercontent.com/7007181/208226792-baa87148-876c-4f8c-8377-241ec24c32d2.png)
Except for the video area in the picture, it is drawn by skia.
This is just a test project for cross-platform video playback, a proof of feasibility. After waiting for flutter to implement video playback, I will consider whether to continue to improve my current solution based on the actual effect.

**Comment by alexmercerind** [comment]
I mean that's okay. libmpv is meant to render onto open-gl context after all.
What I mean is that ANGLE won't work with Direct3D 9.

Even Flutter seems to use software rendering in my VM.
See non-working removed D3D 9 fallback: https://github.com/flutter/engine/pull/29533.

For now, I will just support Windows 10 or higher hardware acceleration & fallback to SW rendering on earlier versions.
I will make my work public soon & you can consider improving.

**Comment by sudongg** [comment]
If I continue my current project, I need to write a UI framework again using skia.
I'll try your project and keep waiting for the official play implementation.
I will not proceed with this project without being sure that Flutter can meet my requirements.

**Comment by alexmercerind** [comment]
Just wanted to give updated here, from latest observations, it is not about ANGLE etc. 
The Texture widget itself is not working on Windows 7 OR DirectX 9 (one of the two is faulty).
I tried to just use the pixel buffer rendering & it is also not showing, forget H/W acceleration D3D or ANGLE.
