### ISSUE TITLE
Compiling issues

### ISSUE THREAD

**Issue by dallas1287** [alexmercerind/flutter-windows-ANGLE-OpenGL-Direct3D-Interop#4]
looks like some of the new changes broke the plugin. Particularly the
`ANGLESurfaceManager::ANGLESurfaceManager(HWND window, int32_t width,
                                         int32_t height,
                                         IDXGIAdapter* adapter = nullptr)
`
throws an error with the redefinition of the adapter parameter. That's an easy fix but the more annoying one after correcting that is the 
`auto adapter = registrar_->GetView()->GetGraphicsAdapter();`
call at line 98 of flutter_windows_angle_d3d_texture_plugin.cc says the GetGraphicsAdapter is not a member of FlutterView.
Am I on an island here or is this known?

**Comment by dallas1287** [comment]
nvm i take it back. I wasn't on master. Does anyone know when the GetGraphicsAdapter() that lets you get that IDXGIAdapter will be available on stable?

**Comment by alexmercerind** [comment]
> NVM I take it back. I wasn't on master. Does anyone know when the `GetGraphicsAdapter()` that lets you get that `IDXGIAdapter` will be available on stable?

I don't really know.
However, now that I look back, using this API isn't really necessary, you can query the adapter directly from ANGLE.

**Comment by alexmercerind** [comment]
Or remove that call & just pass a `nullptr`.
I did write code to automatically select (not from ANGLE but from Direct3D), see: 

https://github.com/alexmercerind/flutter-windows-ANGLE-OpenGL-Direct3D-Interop/blob/fa0572633235f9d69409471e323678af1c501173/windows/angle_surface_manager.cc#L111-L128

**Comment by alexmercerind** [comment]
Also, this is just a demo repository. Use the new `ANGLESurfaceManager` in my this repository:

https://github.com/alexmercerind/media_kit

**This is MIT licensed, not Unlicense.**

The `ANGLESurfaceManager` in this handles context, surface etc. correctly & accounts for resize etc. too.
